apiVersion: v1
kind: Namespace
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    istio-injection: enabled
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-app-quota
  namespace: nginx-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "2"
