apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app-monitor
  namespace: nginx-app
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: monitoring
    release: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/name: nginx-metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - nginx-app
