apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-service-account
  namespace: nginx-app
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: service-account
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
  namespace: nginx-app
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
  namespace: nginx-app
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: nginx-app
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
