apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: nginx-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nginx-demo
  name: nginx-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: nginx-demo
subjects:
- kind: ServiceAccount
  name: nginx-sa
  namespace: nginx-demo
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-netpol
  namespace: nginx-demo
spec:
  podSelector:
    matchLabels:
      app: nginx-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 80
  - from:
    - podSelector:
        matchLabels:
          app: nginx-backend
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: nginx-backend
    ports:
    - protocol: TCP
      port: 80
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-backend-netpol
  namespace: nginx-demo
spec:
  podSelector:
    matchLabels:
      app: nginx-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-frontend
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-limits
  namespace: nginx-demo
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
  namespace: nginx-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-frontend-pdb
  namespace: nginx-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-backend-pdb
  namespace: nginx-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-backend
