apiVersion: v1
kind: Secret
metadata:
  name: azure-aks-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mmparmar553/azure-aks-demo.git
  name: azure-aks-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-aks-demo-repo-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
data:
  repository.yaml: |
    repositories:
    - url: https://github.com/mmparmar553/azure-aks-demo.git
      name: azure-aks-demo
      type: git
